{
  "hash": "b4a7c5eb29824103f161ec86de47ba36",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"3: Compute the Standardize Precipitation Index based on spatial point.\"\n---\n\n\n\n\n<br>\n\n## Introduction\n\nIn this tutorial, we extract the CHIRPS precipitation observations in Suriname, based on the centroids of the Principal Sampling Units (PSU) of the Suriname Survey of Living Conditions for the years 2016/17 and 2022. Based on the extracted precipitation, the tutorial shows how to compute the Standardized Precipitation Index (SPI) and merge it with the survey based on the date of interviews.\n\n## Code\n\n### Set Up\n\nWe start by setting up the stage for our analysis.\n\nFirst, we load the necessary packages. We load only `climatic4economist` package that contains several functions meant to extract and merge spatial variables with surveys. During the tutorial we will use other packages but instead of loading all the package at the begging we will call specific function each time.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(climatic4economist)\n```\n:::\n\n\n\n\nIn the setup, we also want to create the paths to the various data sources and load the necessary functions for extraction. Note `..` means one step back to the folder directory, i.e. one folder back.\n\nNote that how to set up the paths depends on your folder organization but there are overall two approaches:\n\n1.  you can use the `R project`, by opening the project directly you don't need to set up the path to the project. Automatically the project figures out on its own where it is located in the computer and set that path as working folder.\n2.  you can manually set the working folder with the function `setwd()`.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# path to data folder\npath_to_data <- file.path(\"..\", # <1>\n                          \"..\", \"data\") # <2>\n\n# survey \npath_to_wave_1 <- file.path(path_to_data, \"survey\", \"suriname\", \"wave 1\",\n                            \"RT001_Public.dta\")\n\npath_to_wave_2 <- file.path(path_to_data, \"survey\", \"suriname\", \"wave 2\", \n                            \"2022 RT001_Housing_plus.dta\")\n\n# administrative division\npath_to_adm_div <- file.path(path_to_data, \"adm_div\", \"GAUL\")\n\n# weather variables\npath_to_pre_monthly <- file.path(path_to_data, \"weather\", \"CHIRPS\", \"monthly\",\n                                 \"chirps-v2.0.monthly.nc\")\n# to result folder\npath_to_result <- file.path(path_to_data, \"result\")\n```\n:::\n\n\n\n\n1.  concatenate the string to make a path\n2.  `..` means one folder back\n\n<br>\n\n### Read the data\n\n#### Survey\n\nWe begin by reading the surveys, which in this case consist of two waves with potentially different locations. As a result, we need to load both waves. The waves are stored as `dta` files, so we use the `haven::read_dta()` function to read them.\n\nWe only need the hhid, the survey coordinates, and the interview dates. We use `dplyr::select()` to choose these variables. This passage is optional and we bring with us all the variables, but we won't use them. Note that the first wave does not include the interview date.\n\nWe combine the two waves using `dplyr::bind_rows()`.\n\nWe can use the `head()` function to preview the data and see how it looks.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwave_1 <- haven::read_dta(path_to_wave_1) |>\n    dplyr::select(hhid, lat_cen, long_cen) |> \n    dplyr::mutate(wave = 1)\n\nwave_2 <- haven::read_dta(path_to_wave_2) |>\n    dplyr::select(hhid, end_date_n, lat_cen, long_cen) |>\n    dplyr::mutate(wave = 2)\n\nsurvey <- dplyr::bind_rows(wave_1, wave_2)\n\nhead(survey)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 5\n     hhid lat_cen long_cen  wave end_date_n\n    <dbl>   <dbl>    <dbl> <dbl> <date>    \n1 1010031    5.82    -55.2     1 NA        \n2 1010041    5.82    -55.2     1 NA        \n3 1010051    5.82    -55.2     1 NA        \n4 1010061    5.82    -55.2     1 NA        \n5 1010121    5.82    -55.2     1 NA        \n6 1010131    5.82    -55.2     1 NA        \n```\n\n\n:::\n:::\n\n\n\n\n#### Aministrative Divisions\n\nWe read the spatial file containing the national borders of Suriname, we use `read_GAUL()` to load it. By printing the spatial data, we can obtain key information, such as the dimensions (number of rows and variables), the geometry (which indicates the type of spatial object), and the coordinate reference system (CRS), which links the coordinates to precise locations on the Earth's surface. The CRS is particularly important when working with different spatial datasets, as mismatched CRSs can prevent the datasets from aligning correctly.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nadm_div <- read_GAUL(path_to_adm_div, iso = \"SUR\", lvl = 2)\nadm_div\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n class       : SpatVector \n geometry    : polygons \n dimensions  : 62, 4  (geometries, attributes)\n extent      : -58.04987, -53.97982, 1.83114, 6.004546  (xmin, xmax, ymin, ymax)\n source      : GAUL-SUR-ADM2.geojson\n coord. ref. : lon/lat WGS 84 (EPSG:4326) \n names       : ID_adm_div   iso  adm_div_1  adm_div_2\n type        :      <chr> <chr>      <chr>      <chr>\n values      :          1   SUR Brokopondo  Brownsweg\n                        2   SUR Brokopondo    Centrum\n                        3   SUR Brokopondo Klaaskreek\n```\n\n\n:::\n:::\n\n\n\n\n#### Weather\n\nFinally, we load the precipitation data. Climatic data typically comes in the form of raster data. A raster represents a two-dimensional image as a rectangular matrix or grid of pixels. These are spatial rasters because they are georeferenced, meaning each pixel (or \"cell\" in GIS terms) represents a square region of geographic space. The value of each cell reflects a measurable property (either qualitative or quantitative) of that region. In this case, the values are monthly precipitation that fell in that region. We use the function `terra::rast()` to load the raster data.\n\nThis particular raster has global coverage, so we crop it to focus on the country area to reduce its size. Although this step is not strictly necessary, it helps decrease the memory load and makes visualizations more manageable. We use the function `crop_with_buffer()` for this purpose.\n\nWhen we print the raster, we obtain several key details. The dimension tells us how many cells the raster consists of and the number of layers, each layer corresponds to a particular months for which the observations were made. We also get the spatial resolution, which defines the size of each square region in geographic space, and the coordinate reference system (CRS). Given the importance of the CRS, we extract it using `terra::crs()` and save it for later use.\n\nWe also rename the raster layers to reflect the corresponding dates for each layer, as this is useful if we want to track the dates. We use `terra::time()` to extract the dates.\n\n::: callout-note\nNote that rasters can store time information in different ways, so it may not always be possible to retrieve dates in this manner. A common alternative is for dates to be embedded in the layer names, in which case we wouldn’t need to rename the layers.\n:::\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nweather_monthly <- terra::rast(path_to_pre_monthly) |>\n    crop_with_buffer(adm_div)\nweather_monthly\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nclass       : SpatRaster \nsize        : 83, 81, 527  (nrow, ncol, nlyr)\nresolution  : 0.05, 0.05  (x, y)\nextent      : -58.05, -54, 1.85, 6  (xmin, xmax, ymin, ymax)\ncoord. ref. : lon/lat WGS 84 (CRS84) (OGC:CRS84) \nsource(s)   : memory\nvarname     : precip (Climate Hazards group InfraRed Precipitation with Stations) \nnames       :  precip_1,  precip_2,  precip_3, precip_4, precip_5,   precip_6,      ... \nmin values  :  36.21083,  49.09035,  34.04647, 153.5361, 103.0583,   90.83206,      ... \nmax values  : 403.70178, 653.45990, 345.78024, 622.1295, 795.1603, 1034.43372,      ... \nunit        : mm/month \ntime (days) : 1981-01-01 to 2024-11-01 (527 steps) \n```\n\n\n:::\n\n```{.r .cell-code}\nnames(weather_monthly) <- terra::time(weather_monthly)\nweather_monthly\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nclass       : SpatRaster \nsize        : 83, 81, 527  (nrow, ncol, nlyr)\nresolution  : 0.05, 0.05  (x, y)\nextent      : -58.05, -54, 1.85, 6  (xmin, xmax, ymin, ymax)\ncoord. ref. : lon/lat WGS 84 (CRS84) (OGC:CRS84) \nsource(s)   : memory\nvarname     : precip (Climate Hazards group InfraRed Precipitation with Stations) \nnames       : 1981-01-01, 1981-02-01, 1981-03-01, 1981-04-01, 1981-05-01, 1981-06-01,      ... \nmin values  :   36.21083,   49.09035,   34.04647,   153.5361,   103.0583,   90.83206,      ... \nmax values  :  403.70178,  653.45990,  345.78024,   622.1295,   795.1603, 1034.43372,      ... \nunit        : mm/month \ntime (days) : 1981-01-01 to 2024-11-01 (527 steps) \n```\n\n\n:::\n:::\n\n\n\n\n<br>\n\n### Georeference the survey\n\nAs we've mentioned, the weather data is georeferenced, so we need to ensure the same for the survey data. Since many households share the same coordinates, they are linked to the same weather events. To reduce computation time, we extract data only for the unique coordinates, rather than for each household. Moreover, we must ensure that we can later associate the correct weather data with the right household, we do this by creating an merging variable called `ID`.\n\nThis is handled by the `prepare_coord()` function, which requires the coordinates' variable names as input.\n\nWe can print the result to check the transformation. The new column, `ID`, is created by `prepare_coord()` and identifies each unique coordinate. This is used to merge the weather data with the household data.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsrvy_coord <- prepare_coord(survey, lat_var = lat_cen, lon_var = long_cen)\nsrvy_coord\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4,535 × 6\n   ID           hhid lat_cen long_cen  wave end_date_n\n   <chr>       <dbl>   <dbl>    <dbl> <dbl> <date>    \n 1 1     23903250101    3.85    -54.2     2 2022-12-06\n 2 1     23903250201    3.85    -54.2     2 2022-12-06\n 3 1     23903250301    3.85    -54.2     2 2022-12-06\n 4 1     23903250401    3.85    -54.2     2 2022-12-07\n 5 1     23903252201    3.85    -54.2     2 2022-12-07\n 6 1     23903252301    3.85    -54.2     2 2022-12-06\n 7 1     23903252501    3.85    -54.2     2 2022-12-06\n 8 1     23903252601    3.85    -54.2     2 2022-12-06\n 9 1     23903253301    3.85    -54.2     2 2022-12-07\n10 1     23903253501    3.85    -54.2     2 2022-12-06\n# ℹ 4,525 more rows\n```\n\n\n:::\n:::\n\n\n\n\nOnce we have the unique coordinates, we are ready to transform them into spatial points using the `georef_coord()` function. When performing this transformation, it's crucial to set the correct CRS, which must match that of the weather data. The CRS is provided as an argument of the function, using the previously saved CRS from the weather data. Also the `georef_coord()` function requires the coordinates' variable names as input.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsrvy_geo <- georef_coord(srvy_coord,\n                          geom = c(\"long_cen\", \"lat_cen\"),\n                          crs = \"EPSG:4326\")\nsrvy_geo\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n class       : SpatVector \n geometry    : points \n dimensions  : 688, 1  (geometries, attributes)\n extent      : -57.05207, -54.05524, 3.849064, 5.943465  (xmin, xmax, ymin, ymax)\n coord. ref. : lon/lat WGS 84 (EPSG:4326) \n names       :    ID\n type        : <chr>\n values      :     1\n                   2\n                   3\n```\n\n\n:::\n:::\n\n\n\n\nNote how there are 688 rows. These are the unique locations from the survey.\n\n<br>\n\n### Plot\n\nA good practice when working with spatial data is to plot it. This is the best way to verify that everything is working as expected.\n\nFirst, we plot the survey coordinates to ensure they are correctly located within the country and to examine their spatial distribution.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nterra::plot(adm_div, col = \"grey\", main = \"Suriname and PSU centroids\")\nterra::points(srvy_geo, col = \"gold\", alpha = 0.5, cex = 0.5)\n```\n\n::: {.cell-output-display}\n![](spi_by_points_files/figure-html/plot_survey_geo-1.png){width=672}\n:::\n:::\n\n\n\n\nWe confirm that the survey locations are within the country borders, which is great! We also observe that the spatial distribution of survey coordinates is neither random nor uniform; most are concentrated near the capital and along the coast.\n\nNext, we plot a layer of the precipitation data to see how it overlaps with the spatial coordinates.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nterra::plot(weather_monthly, \"2024-10-01\", col = terra::map.pal(\"water\"),\n            main = \"Monthly precipitation at 2024-10 and survey location\")\nterra::lines(adm_div, col = \"white\", lwd = 2)\nterra::points(srvy_geo, col = \"red\", alpha = 0.5, cex = 0.5)\n```\n\n::: {.cell-output-display}\n![](spi_by_points_files/figure-html/plot_precipitation-1.png){width=672}\n:::\n:::\n\n\n\n\nOnce again, the survey coordinates align with the precipitation data, which is great! We can also observe the high spatial resolution of the CHIRPS dataset. However, despite this high resolution, some survey coordinates still fall within the same cell.\n\n<br>\n\n### Extract\n\nNext, we extract the weather data based on the survey coordinates using the `extract_by_coord()` function. This function requires the raster with the weather data and the georeferenced coordinates as inputs.\n\nLooking at the result, we see first the `ID` column, that identifies the unique survey coordinates. The second and third column are the coordinates of the cells. The other columns contain the weather observations over time specific to each coordinate.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npre_coord <- extract_by_coord(raster = weather_monthly, \n                              coord = srvy_geo)\npre_coord\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 688 × 530\n   ID    x_cell y_cell X1981_01_01 X1981_02_01 X1981_03_01 X1981_04_01\n   <chr>  <dbl>  <dbl>       <dbl>       <dbl>       <dbl>       <dbl>\n 1 1      -54.2   3.82        255.        260.       133.         359.\n 2 2      -55.5   3.92        225.        249.        87.2        380.\n 3 3      -55.5   3.97        184.        239.        86.9        384.\n 4 4      -55.5   4.02        186.        251.        86.3        368.\n 5 5      -55.5   4.02        186.        251.        86.3        368.\n 6 6      -55.4   4.02        167.        265.        86.6        379.\n 7 7      -54.8   4.07        140.        261.       107.         347.\n 8 8      -55.4   4.12        186.        257.        96.2        347.\n 9 9      -55.4   4.17        210.        228.        87.0        376.\n10 10     -55.2   4.17        213.        260.        90.0        339.\n# ℹ 678 more rows\n# ℹ 523 more variables: X1981_05_01 <dbl>, X1981_06_01 <dbl>,\n#   X1981_07_01 <dbl>, X1981_08_01 <dbl>, X1981_09_01 <dbl>, X1981_10_01 <dbl>,\n#   X1981_11_01 <dbl>, X1981_12_01 <dbl>, X1982_01_01 <dbl>, X1982_02_01 <dbl>,\n#   X1982_03_01 <dbl>, X1982_04_01 <dbl>, X1982_05_01 <dbl>, X1982_06_01 <dbl>,\n#   X1982_07_01 <dbl>, X1982_08_01 <dbl>, X1982_09_01 <dbl>, X1982_10_01 <dbl>,\n#   X1982_11_01 <dbl>, X1982_12_01 <dbl>, X1983_01_01 <dbl>, …\n```\n\n\n:::\n:::\n\n\n\n\nAgain we have a row for each unique location from the survey. However, if we want to know how many different cells there are we can look unique cell coordinates.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nunique_cell <- pre_coord |>\n  dplyr::distinct(x_cell, y_cell)\nnrow(unique_cell)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 107\n```\n\n\n:::\n:::\n\n\n\n\nWe see that now the number of rows is 107, this is the actual different weather observation that we can merge with the survey.\n\n<br>\n\n### Compute the SPI\n\nWe now compute the SPI with the function `compute_spi()`. This function requires the precipitation time series for each location and the time scale at which the SPI is computed.\n\nTo compute the SPI, it is recommended to use at least 30 years of observation to ensure a good estimation of the parameters. More years can strength the estimation but the results can be affected by climate change: if there have been a change in the climate parameters, old observations might be not indicative of the current situation affecting the estimation. There are no clear rule on this, so we leave add the possibility to select the time range of observation with the function `select_by_dates()`. The function requires both or just one between the starting date, `from`, and the end date `to`. If both are provide the the function select between the two dates, if only `from` is provided the function selects all date after, and if only `to` is provided the function selects all date before.\n\nLooking at the result, we see first is the `ID` column, that we will use to merge back with the survey. The other columns contain the SPI observations over time specific to each coordinate.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# coord  <- select_by_dates(coord, from = \"1991-01-01\", to = \"2023-01-01\") \n\nspi3 <- compute_spi(pre_coord, time_scale = 3)\nspi3\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 688 × 530\n   ID    x_cell y_cell X1981_01_01 X1981_02_01 X1981_03_01 X1981_04_01\n   <chr>  <dbl>  <dbl>       <dbl>       <dbl>       <dbl>       <dbl>\n 1 1      -54.2   3.82          NA          NA     -0.0896       0.333\n 2 10     -55.2   4.17          NA          NA     -0.173        0.208\n 3 100    -55.2   5.67          NA          NA      0.124        0.624\n 4 101    -55.4   5.72          NA          NA      0.0581       0.918\n 5 102    -55.2   5.72          NA          NA      0.0618       0.843\n 6 103    -55.2   5.72          NA          NA      0.0618       0.843\n 7 104    -55.2   5.72          NA          NA      0.0618       0.843\n 8 105    -55.2   5.72          NA          NA      0.0618       0.843\n 9 106    -55.1   5.72          NA          NA      0.121        0.994\n10 107    -55.1   5.72          NA          NA      0.121        0.994\n# ℹ 678 more rows\n# ℹ 523 more variables: X1981_05_01 <dbl>, X1981_06_01 <dbl>,\n#   X1981_07_01 <dbl>, X1981_08_01 <dbl>, X1981_09_01 <dbl>, X1981_10_01 <dbl>,\n#   X1981_11_01 <dbl>, X1981_12_01 <dbl>, X1982_01_01 <dbl>, X1982_02_01 <dbl>,\n#   X1982_03_01 <dbl>, X1982_04_01 <dbl>, X1982_05_01 <dbl>, X1982_06_01 <dbl>,\n#   X1982_07_01 <dbl>, X1982_08_01 <dbl>, X1982_09_01 <dbl>, X1982_10_01 <dbl>,\n#   X1982_11_01 <dbl>, X1982_12_01 <dbl>, X1983_01_01 <dbl>, …\n```\n\n\n:::\n:::\n\n\n\n\nIf we want to calculate the SPI with time scale equal to one, we just need to change the `time_scale` argument.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nspi1 <- compute_spi(pre_coord, time_scale = 1)\nspi1\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 688 × 530\n   ID    x_cell y_cell X1981_01_01 X1981_02_01 X1981_03_01 X1981_04_01\n   <chr>  <dbl>  <dbl>       <dbl>       <dbl>       <dbl>       <dbl>\n 1 1      -54.2   3.82      0.115        0.543      -0.801       0.913\n 2 10     -55.2   4.17     -0.0471       0.737      -1.06        0.688\n 3 100    -55.2   5.67      0.0636       0.592      -0.170       0.838\n 4 101    -55.4   5.72     -0.722        1.04        0.136       0.755\n 5 102    -55.2   5.72     -0.478        1.06       -0.131       0.755\n 6 103    -55.2   5.72     -0.478        1.06       -0.131       0.755\n 7 104    -55.2   5.72     -0.478        1.06       -0.131       0.755\n 8 105    -55.2   5.72     -0.478        1.06       -0.131       0.755\n 9 106    -55.1   5.72     -0.494        1.24       -0.135       0.853\n10 107    -55.1   5.72     -0.494        1.24       -0.135       0.853\n# ℹ 678 more rows\n# ℹ 523 more variables: X1981_05_01 <dbl>, X1981_06_01 <dbl>,\n#   X1981_07_01 <dbl>, X1981_08_01 <dbl>, X1981_09_01 <dbl>, X1981_10_01 <dbl>,\n#   X1981_11_01 <dbl>, X1981_12_01 <dbl>, X1982_01_01 <dbl>, X1982_02_01 <dbl>,\n#   X1982_03_01 <dbl>, X1982_04_01 <dbl>, X1982_05_01 <dbl>, X1982_06_01 <dbl>,\n#   X1982_07_01 <dbl>, X1982_08_01 <dbl>, X1982_09_01 <dbl>, X1982_10_01 <dbl>,\n#   X1982_11_01 <dbl>, X1982_12_01 <dbl>, X1983_01_01 <dbl>, …\n```\n\n\n:::\n:::\n\n\n\n\n<br>\n\n### Merge with survey\n\nNow, we combine the extracted weather data with the survey data using `ID` as the key matching variable.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nspi3_survey <- merge_with_survey(srvy_coord, spi3)\n\nspi3_survey\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4,535 × 535\n   ID           hhid lat_cen long_cen  wave end_date_n x_cell y_cell X1981_01_01\n   <chr>       <dbl>   <dbl>    <dbl> <dbl> <date>      <dbl>  <dbl>       <dbl>\n 1 1     23903250101    3.85    -54.2     2 2022-12-06  -54.2   3.82          NA\n 2 1     23903250201    3.85    -54.2     2 2022-12-06  -54.2   3.82          NA\n 3 1     23903250301    3.85    -54.2     2 2022-12-06  -54.2   3.82          NA\n 4 1     23903250401    3.85    -54.2     2 2022-12-07  -54.2   3.82          NA\n 5 1     23903252201    3.85    -54.2     2 2022-12-07  -54.2   3.82          NA\n 6 1     23903252301    3.85    -54.2     2 2022-12-06  -54.2   3.82          NA\n 7 1     23903252501    3.85    -54.2     2 2022-12-06  -54.2   3.82          NA\n 8 1     23903252601    3.85    -54.2     2 2022-12-06  -54.2   3.82          NA\n 9 1     23903253301    3.85    -54.2     2 2022-12-07  -54.2   3.82          NA\n10 1     23903253501    3.85    -54.2     2 2022-12-06  -54.2   3.82          NA\n# ℹ 4,525 more rows\n# ℹ 526 more variables: X1981_02_01 <dbl>, X1981_03_01 <dbl>,\n#   X1981_04_01 <dbl>, X1981_05_01 <dbl>, X1981_06_01 <dbl>, X1981_07_01 <dbl>,\n#   X1981_08_01 <dbl>, X1981_09_01 <dbl>, X1981_10_01 <dbl>, X1981_11_01 <dbl>,\n#   X1981_12_01 <dbl>, X1982_01_01 <dbl>, X1982_02_01 <dbl>, X1982_03_01 <dbl>,\n#   X1982_04_01 <dbl>, X1982_05_01 <dbl>, X1982_06_01 <dbl>, X1982_07_01 <dbl>,\n#   X1982_08_01 <dbl>, X1982_09_01 <dbl>, X1982_10_01 <dbl>, …\n```\n\n\n:::\n:::\n\n\n\n\nWe are back at 4535, which matches the original survey.\n\n<br>\n\n### Select based on the interview\n\nNow that we have merged the SPI values with the survey, we can select just the relevant observations.\n\nIf we want to select just a subsets of observations we can use the `select_by_dates()` function. If we want to select based on the date of interview of the survey, we can use `select_by_interview()`. This last function requires the variable that contains the dates of interview and the interval to select based on the dates. The interval must be express in number of months or in number years. The `wide` argument specifies how the output should be reported, in wide with each time observation as separate columns, or long, with all observation in one column.\n\n> Note that current version of the `select_by_interview()` functions drops the observations with missing date of interview.\n\nWhat is relevant depends on the particular application, but we can agree that we don't want to assign weather observations that happened after the interviews, as these cannot influence the answers.\n\nIn this tutorial we select the 12 months before the interviews using the function `select_by_interview()`. The argument `interview` select the variable containing the date of interviews, and the argument `interval` defines how back in time the function needs to select the observations.\n\nIf there are missing observations for the date of interviews, the function warns us that these observations are dropped.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nspi3_hh <- select_by_interview(spi3_survey,\n                               interview = end_date_n,\n                               interval = \"1 year\",\n                               wide = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMissing interview are dropped!\n```\n\n\n:::\n:::\n\n\n\n\n<br>\n\n### Save\n\nThe final step of the code is to save the result. In this case, we save it as a `dta` file using the `haven::write_dta()` function.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhaven::write_dta(spi1_survey, file.path(path_to_result, \"spi_1.dta\"))\n\nhaven::write_dta(spi3_hh, file.path(path_to_result, \"spi_3.dta\"))\n```\n:::\n\n\n\n\n<br><br>\n\n## Take home messages\n\n-   When working with multiple spatial data:\n\n    1.  remember to control the Coordinate Reference System of all dataset\n    2.  plot the data to check everything is going well\n\n-   based on the typology of data we use different function to read them\n\n    -   for `dta` use `haven::read_dta() or` and `haven::_write_dta()`\n    -   for spatial vectors `read_GAUL()` for administrative divisions in specific country and level, otherwise `terra::vect()`\n    -   for spatial raster use `terra::rast()`\n\n-   Extraction\n\n    -   since many household share the same locations, we take advantage of this by extracting the weather data only at the unique locations, we achieve this with the function `prepare_coord()`.\n    -   same of these unique locations may fall within the same value cells, so the actual information might be even lower.\n\n<br><br>\n\n## Appendix\n\n### Want to know about the data?\n\n#### Precipitation\n\nMonthly and daily precipitation from Climate Hazards Group InfraRed Precipitation with Station data (CHIRPS)[^1] is a 35+ year quasi-global rainfall data set. Spanning 50°S-50°N (and all longitudes) and ranging from 1981 to near-present, CHIRPS incorporates in-house climatology, CHPclim, 0.05° resolution satellite imagery, and in-situ station data to create gridded rainfall time series for trend analysis and seasonal drought monitoring.\n\n[^1]: Funk, C.C., Peterson, P.J., Landsfeld, M.F., Pedreros, D.H., Verdin, J.P., Rowland, J.D., Romero, B.E., Husak, G.J., Michaelsen, J.C., and Verdin, A.P., 2014, A quasi-global precipitation time series for drought monitoring: U.S. Geological Survey Data Series 832, 4 p. http://pubs.usgs.gov/ds/832/\n\nData can be downloaded from [here](https://data.chc.ucsb.edu/products/CHIRPS-2.0/global_monthly/netcdf/) while extra information are available [here](https://www.chc.ucsb.edu/).\n\n| feature             | value                 |\n|:--------------------|:----------------------|\n| spatial resolution  | 0.05 x 0.05 (\\~ 5 km) |\n| temporal resolution | monthly or daily      |\n| temporal frame      | 1981 - near present   |\n| unit of measure     | mm/month or mm/day    |\n\n#### Surveys\n\nSuriname Survey of Living Conditions. The 2022 Suriname Survey of Living Conditions is a joint survey made by The Inter-American Development Bank (IDB) and the World Bank. The 2022 Suriname Survey of Living Conditions - administered to a nationally representative sample, which included 7,713 individuals from 2,540 households - was developed to support poverty analysis as well as policy planning and is a helpful tool for policy makers to facilitate fact-based decision making. The survey’s design and execution were financed by the IDB, while the World Bank and IDB are joining forces to analyze data and produce initial findings.\n\nThe Suriname Survey of Living Conditions (SSLC) 2016/17 is an effort of the Inter-American Development Bank (IDB) with the support of the EnergieBedrijvan Suriname’s (state-owned electrical company of Suriname) and the Central Bank of Suriname. It visited about 2,000 households from October 2016 through September 2017 and collected data on the most important dimensions of welfare, which will support evidence-based policy making in areas such as education, health, housing, employment and poverty alleviation. The survey also gathered information on the consumption patterns, income and expenditures of the Surinamese households, intended to update the Consumption Price Index basket and inform the System of National Accounts.\n\nFor extra info look [here](https://openknowledge.worldbank.org/entities/publication/2d0e6975-2f85-4d12-83fa-4f75c617cf89) and [here](https://webapps.ilo.org/surveyLib/index.php/catalog/7499).\n\n#### Adminitrative boundaries\n\nThe Global Administrative Unit Layers (GAUL) 2024 is a vector dataset compiling the most recent available information on administrative boundaries from multiple sources, produced by FAO from 2022 to 2024 in the framework of the Hand-in-Hand Initiative and the Geospatial Data Platform activities.\n\nThe GAUL 2024 aims at maintaining global layers with a unified coding system at country, first (e.g. departments), and second (e.g. districts) administrative levels. The data, sourced and processed from the United Nations Second Administrative Level Boundaries (UN-SALB) programme and from other relevant data sources, was complemented by the UN-FAO-CSI AgroInformatics Geospatial Analysis team with data from official geospatial data producers. Country boundaries were processed against UN official recognized borders (UN-map 2018), and the administrative subdivisions were checked for geometry and topology, then corrected and validated. The administrative boundaries dataset at level 1 and 2 (Sub-national level) is part of the Global Administrative Unit Layers (GAUL) dataset series which includes information on administrative units for all the countries in the world, providing a contribution to the standardization of the spatial dataset representing administrative units. The administrative boundaries at the level 1 dataset distinguishes States, Provinces, Departments and equivalent. The administrative boundaries at the level 2 dataset distinguishes Districts and equivalent.\n\nSuggested citation:\n\n-   FAO. 2024. Global Administrative Unit Layers (GAUL). \\[Accessed on \\[DD Month YYYY\\]\\]. https://data.apps.fao.org/?lang=en. Licence: CC-BY-4.0\n\nIt is possible to find additional information:\n\n-   [here](https://data.apps.fao.org/catalog/dataset/global-administrative-unit-layers-gaul-2024)\n\nThe data can be freely download from\n\n-   [here](https://data.apps.fao.org/catalog/dataset/34f97afc-6218-459a-971d-5af1162d318a).\n",
    "supporting": [
      "spi_by_points_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}